-
    name: 'Execute a date command on localhost'
    hosts: localhost
    tasks:
        -
            name: 'Execute a date command'
            script: /home/gcptrial00/test.sh
            become : yes
