-
    name: 'Execute a date command on localhost'
    hosts: localhost
    tasks:
        -
            name: 'Execute a date command'
            command: date
        -
            name: 'Create a new user'
            user:
                name: web_user
                uid: 1040
                group: developers